using System.Drawing;

namespace J.Core;

public static class MyColors
{
    public static readonly Color BarberPoleStripe = Color.FromArgb(118, 122, 135);
    public static readonly Color ButtonAcceptBackgroundHover = Color.FromArgb(71, 177, 232);
    public static readonly Color ButtonAcceptBackgroundNormal = Color.FromArgb(76, 194, 255);
    public static readonly Color ButtonAcceptBackgroundPressed = Color.FromArgb(66, 161, 210);
    public static readonly Color ButtonAcceptBorderHover = Color.FromArgb(85, 183, 234);
    public static readonly Color ButtonAcceptBorderNormal = Color.FromArgb(90, 199, 255);
    public static readonly Color ButtonAcceptForegroundNormal = Color.FromArgb(0, 0, 0);
    public static readonly Color ButtonAcceptForegroundPressed = Color.FromArgb(33, 80, 105);
    public static readonly Color ButtonBackgroundHover = Color.FromArgb(60, 60, 60);
    public static readonly Color ButtonBackgroundNormal = Color.FromArgb(55, 55, 55);
    public static readonly Color ButtonBackgroundPressed = Color.FromArgb(50, 50, 50);
    public static readonly Color ButtonBorder = Color.FromArgb(63, 63, 63);
    public static readonly Color ButtonDisabledBack = Color.FromArgb(35, 35, 35);
    public static readonly Color ButtonDisabledText = Color.FromArgb(160, 160, 160);
    public static readonly Color ButtonFocusOutline = Color.FromArgb(255, 255, 255);
    public static readonly Color ButtonForegroundPressed = Color.FromArgb(208, 208, 208);
    public static readonly Color ButtonText = Color.FromArgb(240, 240, 240);
    public static readonly Color DataGridAlternateRowBackground = Color.FromArgb(45, 45, 45);
    public static readonly Color DataGridBackground = Color.Black;
    public static readonly Color DataGridLines = Color.LightGray;
    public static readonly Color DataGridRowBackground = Color.Black;
    public static readonly Color DataGridSelectionForeground = Color.White;
    public static readonly Color DialogBackground = Color.FromArgb(31, 31, 31);
    public static readonly Color LabelForeground = Color.White;
    public static readonly Color LabelForegroundDisabled = Color.FromArgb(99, 99, 99);
    public static readonly Color Link = Color.FromArgb(0x92, 0xB1, 0xE2);
    public static readonly Color MainFormBackground = Color.FromArgb(38, 38, 38);
    public static readonly Color MenuItemText = Color.White;
    public static readonly Color ProgressBarBackground = Color.FromArgb(90, 95, 110);
    public static readonly Color ProgressBarBorder = Color.Black;
    public static readonly Color ProgressBarFailedBackground = Color.DarkRed;
    public static readonly Color ProgressBarForeground = Color.FromArgb(0x00, 0x7A, 0xD7);
    public static readonly Color ProgressBarSuccessBackground = Color.DarkGreen;
    public static readonly Color TabBorder = Color.FromArgb(60, 60, 60);
    public static readonly Color TabInactiveText = Color.FromArgb(180, 180, 180);
    public static readonly Color TabPageBackground = Color.FromArgb(43, 43, 43);
    public static readonly Color TabSelected = Color.FromArgb(43, 43, 43);
    public static readonly Color TabText = Color.FromArgb(240, 240, 240);
    public static readonly Color TabUnselected = Color.FromArgb(38, 38, 38);
    public static readonly Color TextBoxBackground = Color.FromArgb(51, 51, 51);
    public static readonly Color TextBoxBorder = Color.FromArgb(53, 53, 53);
    public static readonly Color TextBoxBottomBorder = Color.FromArgb(156, 156, 156);
    public static readonly Color TextBoxCueText = Color.FromArgb(0x90, 0x90, 0x90);
    public static readonly Color TextBoxFocusedBackground = Color.FromArgb(32, 32, 32);
    public static readonly Color TextBoxFocusedBottomBorder = Color.FromArgb(76, 194, 255);
    public static readonly Color TextBoxText = Color.FromArgb(255, 255, 255);
    public static readonly Color ToolStripActiveBackground = Color.White;
    public static readonly Color ToolStripActiveForeground = Color.Black;
    public static readonly Color ToolStripBackground = Color.FromArgb(44, 44, 44);
    public static readonly Color ToolStripForeground = Color.White;
    public static readonly Color ToolStripHover = Color.FromArgb(56, 56, 56);
    public static readonly Color ToolStripPress = Color.FromArgb(52, 52, 52);
    public static readonly Color ToolStripTabButtonBackgroundDark = Color.FromArgb(45, 45, 45);
    public static readonly Color ToolStripTabButtonTabInactiveBg = Color.FromArgb(65, 65, 65);
    public static readonly Color ToolStripTabButtonTextActive = Color.Black;
    public static readonly Color ToolStripTabButtonTextInactive = Color.FromArgb(210, 210, 210);
    public static readonly Color WebListSelection = Color.FromArgb(0x00, 0x7A, 0xD7);
}
